apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail
  namespace: default
  labels:
    app: airtrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
        - name: airtrail
          image: johly/airtrail:v3.2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: airtrail-config
            - secretRef:
                name: airtrail-secret
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
