apiVersion: v1
kind: Service
metadata:
  name: airtrail-service
  namespace: default
  labels:
    app: airtrail
    component: backend
spec:
  selector:
    app: airtrail
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
