apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airtrail-db-pvc-claim
  namespace: default
spec:
  storageClassName: postgres-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
