apiVersion: v1
kind: Service
metadata:
  name: airtrail-postgres
  namespace: default
  labels:
    app: airtrail
    component: postgres
spec:
  selector:
    app: airtrail-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
