apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail-postgres
  namespace: default
  labels:
    app: airtrail-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtrail-db
  template:
    metadata:
      labels:
        app: airtrail-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "{{ POSTGRES_USER }}"]
            periodSeconds: 5
            failureThreshold: 20
          env:
            - name: PGDATA
              value: /var/lib/postgresql/pgdata
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: airtrail-db-pvc-claim
